
  var list = ["File download at"
  "Error downloading file"
  "Downloading"
  "File downloaded successfully"
  "XCash"
  "No action id found"
  "Are you sure want to reject?"
  "Yes"
  "No"
  "NID"
  "Sec"
  "My QR Code"
  "QR Scan"
  "Share"
  "Verified User"
  "Download as Image"
  "Your OTP has been expired."
  "Welcome To Xcash Wallet App"
  "Lorem Ipsum is simply dummy text of the printing and type setting industry"
  "Easy Way To Manage Your Money"
  "Lorem Ipsum is simply dummy text of the printing and type setting industry"
  "Easy to view your transaction report"
  "Lorem Ipsum is simply dummy text of the printing and type setting industry"
  "Skip"
  "Next"
  "Get Started"
  "Payment Preview"
  "Invoice Preview"
  "See More"
  "Before Charge"
  "Remaining Balance"
  "Enter transaction no."
  "Quick Links"
  "Latest Transactions"
  "Send to Email"
  "Publish Invoice"
  "Discard Invoice"
  "Welcome Back!"
  "We happy to see you here again. Enter your\nusername and password"
  "Username"
  "Enter username"
  "Password"
  "Enter password"
  "Remember Me"
  "Forgot Password?"
  "Sign In"
  "Don't have an account?"
  "Nickname field can't be empty"
  "Create an Account"
  "Create you account, it takes less than a minute enter your details"
  "Personal Account"
  "Company Account"
  "First Name"
  "Enter first name"
  "Last Name"
  "Last"
  "Enter last name"
  "Country"
  "Enter your country"
  "Mobile Number"
  "E-mail Address"
  "Confirm Password"
  "Enter first Name"
  "Enter last Name"
  "Select Country"
  "Your phone number"
  "Enter email address"
  "Email address can't be empty"
  "Enter confirm Password"
  "Sign Up"
  "Already have an account?"
  "Sign In Now"
  "Sign Up Now"
  "Legal Name of Company"
  "Enter legal name of company"
  "Representative First Name"
  "Representative Last Name"
  "Username"
  "Enter username"
  "Email"
  "Enter email"
  "Address"
  "Enter address"
  "Address can't be empty"
  "Copy"
  "View"
  "Edit"
  "KYC"
  "is required"
  "Choose File"
  "Your KYC is under review"
  "You are already verified"
  "OTP"
  "Enter the otp sent to "
  "Verify"
  "Request again"
  "Tap for Balance"
  "My Wallets"
  "Transfer Money"
  "Add Money"
  "Withdraw Info"
  "Add Money Info"
  "Invoice Payment Url"
  "Add new method"
  "Setup a new withdraw method"
  "Add Items"
  "Exchange"
  "Make Payment"
  "Invoice"
  "Update Invoice"
  "Voucher"
  "Transfer"
  "Request Money"
  "Requested Amount: "
  "Request Amount"
  "Withdraw Charge: "
  "You will get: "
  "You Will Get"
  "Your Balance will be: "
  "Withdrawals"
  "Insights"
  "Money In"
  "Money Out"
  "See All"
  "See all Wallets"
  "See"
  "Voucher Redeem Log"
  "Redeem Log"
  "Data not found"
  "Home"
  "Activity"
  "Total Received"
  "Total Spent"
  "Total Amount"
  "View Transactions"
  "Transaction"
  "Transaction ID"
  "Request to Me"
  "Add Money History"
  "My Voucher"
  "Withdraw History"
  "Invoices"
  "Invoice To"
  "Payment Status"
  "Select Wallet"
  "Agent Username / Email"
  "Receiver Username / Email"
  "Enter agent username / email"
  "Enter receiver username / email"
  "Amount"
  "Exchange Amount"
  "Enter amount"
  "OTP by SMS"
  "OTP by Email"
  "OTP by Google Authentication"
  "Transfer Now"
  "Charge : 50 USD"
  "Min: 50 USD -- Max: 1000 USD"
  "Date"
  "Gateway"
  "Charge"
  "Payable amount"
  "Payable after Charge"
  "Send From Number"
  "Send Money"
  "Status"
  "Screenshot"
  "Add Money Details"
  "Select Gateway"
  "Summery"
  "Payable"
  "Proceed"
  "Exchange Money"
  "Exchange Calculation"
  "Money Out Detail"
  "Agent Username / Email"
  "Payment Details"
  "Merchant Username / Email"
  "Enter merchant username / email"
  "Not Used"
  "Used"
  "Created at : "
  "Used at"
  "Redeem Voucher"
  "Voucher Code"
  "Enter voucher code"
  "Enter OTP Code"
  "Enter Your OTP Code"
  "Please enter voucher code"
  "Redeem"
  "Provide Details"
  "Create Voucher"
  "Published"
  "Discarded"
  "Invoice"
  "Created Date"
  "Issued:"
  "Download"
  "Create Invoice"
  "Invoice Details"
  "Invoice To"
  "Enter invoice to"
  "Invoice to can't be empty"
  "Your Wallet"
  "Please fill out this field"
  "Invoice items"
  "Item Name"
  "Enter item name"
  "My Requests"
  "To me"
  "Wallet Currency"
  "Note"
  "Want to reject?"
  "Want to confirm?"
  "Are you sure want to confirm?"
  "400 IDR will be colorReduced from your IDR wallet."
  "Confirm"
  "Are you sure want to reject?"
  "Request Details"
  "Total Charge"
  "Amount to Request"
  "Request To"
  "Note for Recipient"
  "Type not"
  "Request Now"
  "Withdraw Money"
  "Basic"
  "Payoner"
  "Paypal"
  "Min: "
  "Max: "
  "Limit"
  "Add Withdraw Method"
  "Select Method"
  "Select Currency"
  "Provide a Nick Name"
  "Reset Password"
  "Your new password must different form previous used passwords"
  "New Password"
  "Enter new password"
  "Change Password"
  "Current Password"
  "Enter current password"
  "Save New Password"
  "Terms of Services"
  "Ownership"
  "Support"
  "Warranty"
  "Unauthorized / Illegal Usage"
  "Payment / Refund Policy"
  "Coupon Policy"
  "USD"
  "Select OTP"
  "Continue Download"
  "Submit"
  "Update Method"
  "Name"
  "Phone"
  "Zip Code"
  "Enter your zip code"
  "State"
  "Enter your state"
  "City"
  "Enter your city"
  "Edit Profile"
  "Update Profile"
  "Select Language"
  "Please check investment limit"
  "Confirm to invest on"
  "Invest"
  "Interest"
  "Google Authenticator Code"
  "Two Factor Authentication"
  "Enter 6-digit code from your two factor authenticator APP."
  "Do you want to exit the app?"
  "Has uppercase letter"
  "Has lowercase letter"
  "Has digit"
  "Has special character"
  "Min of 6 characters"
  "Receivable"
  "Conversion Rate"
  "In"
  "will cut from your selected wallet"
  "Username can't be empty"
  "Initiated"
  "Account"
  "Recover Account"
  "We happy to see you here again enter your username and password"
  "Username or Email"
  "Enter your username or email"
  "Not registecolorRed yet?"
  "Create an account"
  "Please fill out this field"
  "To secure your account please provide a secure password"
  "Enter your email or username below to receive a password reset verification code"
  "A 6 digits verification code sent to your email address"
  "View History"
  "Phone No."
  "Password reset email sent to"
  "Email Verification"
  "Please check your email to get a six digit OTP\nOTP will be expired in the next"
  "Didn't receive code?"
  "Resend Code in"
  "Resend Code"
  "Sms Verification"
  "Profile Complete"
  "Enter your"
  "Enter"
  "Deposit Wallet"
  "Interest Wallet"
  "Total Invest"
  "Total Deposit"
  "Total Withdraw"
  "Referral Earnings"
  "Withdrawal Pending"
  "Deposit Pending"
  "Deposit"
  "Investment"
  "Referral"
  "Transactions"
  "History"
  "Plan"
  "Active Invest"
  "View All"
  "All"
  "Plus"
  "Minus"
  "Invested"
  "Next Return"
  "Total Return"
  "every"
  "Deposit Money"
  "Deposit History"
  "Transaction History"
  "TRX"
  "capital will be back"
  "Post Balance"
  "Details"
  "&"
  "Any"
  "Balance Transfer"
  "Balance"
  "xCash Balance"
  "* Estimate total balance based on the most recent conversion rate."
  "Available"
  "Completed Invest"
  "Referral Link"
  "Total"
  "Max Earn"
  "INVEST NOW"
  "Every week for"
  "week"
  "Investment Plan"
  "Copied to Clipboard"
  "Wallet Type"
  "Wallet"
  "Type"
  "Remark"
  "Withdraw Via"
  "Profile"
  "Theme"
  "Settings"
  "Help & Settings"
  "Language"
  "Help"
  "FAQ"
  "Terms & Conditions"
  "Sign Out"
  "Light"
  "Lifetime"
  "Dark"
  "Conversion"
  "Transaction No."
  "Our Privacy Policy"
  "Privacy & Policy"
  "How Long We Retain"
  "What we don't do with your data"
  "Protection Act Compliance"
  "Payment/Refund Policy"
  "Payment Policy"
  "We've sent a verification code to"
   "Your account is verified successfully. Now you can change your password."
  "To recover your account please provide your email or username to find your account"
  "your email address"
  "Reset Your Password"
  "Forget Password"
  "for"
  "Capital"
  "Don't have an account?"
  "Enter username or email"
  "Policies"
  "Verification Failed"
  "Email Verification Failed"
  "Email Verification Success"
  "Login"
  "Registration"
  "Enter your password"
  "KYC Verification"
  "Notifications"
  "KYC Data"
  "Sorry! there are no data to show"
  "Choose option"
  "Gallery"
  "Camera"
  "Gateway"
  "Payment Method"
  "I agree with"
  "Create new password"
  "Please provide a strong password to protect your account"
  "Enter current password"
  "Enter new password"
  "Enter confirm password"
  "Add Withdraw"
  "Enter Amount"
  "Please enter an amount"
  "0.0"
  "Withdraw Method"
  "Withdraw Method Edit"
  "Withdraw Preview"
  "Search by trx id"
  "No Transaction Found"
  "Trx Id"
  "Completed"
  "Cancel"
  "Time"
  "Bank Name"
  "Account Name"
  "Account Number"
  "Routing Number"
  "PAY NOW"
  "No Deposit Found"
  "No Withdraw Found"
  "OTP Verification"
  "Show More"
  "More"
  "success"
  "version"
  "Sign Out Successfully"
  "Enter valid email"
  "Enter your current password"
  "Enter your new password"
  "Password must be contain 1 special character and number"
  "Password doesn't match"
  "Enter first name"
  "Enter last name"
  "Username must be 6 character"
  "Phone Number"
  "Password Verification"
  "Resend the code successfully"
  "Failed to resend code"
  "Something went wrong"
  "No colorRedirect url found"
  "Invalid amount"
  "Search Result"
  "Enter your email or username below to receive a password reset verification code"
  "Please check your email to get a six digit OTP"
  "Please check your phone to get a six digit OTP"
  "OTP will be expired in the next"
  "Verification Success"
  "Enter your username"
  "Enter username"
  "Enter your email"
  "Enter your phone number"
  "Confirm your password"
  "Please enter valid info to create account"
  "Didn't receive the code?"
  "We've sent you an access code to your phone number for SMS verification"
  "Welcome back"
  "Log in with the data that you enter during your registration"
  "Register"
  "Select a country"
  "Request Failed"
  "Invalid user type"
  "Request Success"
  "Request from"
  "Login failed,please try again"
  "Select One"
  "Select"
  "Select from currency"
  "Select to currency"
  "Can't exchange currency in same wallet"
  "Money Exchange Successfully"
  "SMS"
  "No internet connection"
  "Retry"
  "Return"
  "Otp field can't be empty"
  "Sorry something went wrong here, go back and retry after sometimes"
  "second ago"
  "minutes ago"
  "hour ago"
  "days ago"
  "just now"
  "Level"
  "logout"
  "Menu"
  "Write something..."
  "Bad Response Format!"
  "Server Error"
  "Unauthorized"
  "your email"
  "Password reset email sent to "
  "Password change successfully"
  "Deposit Limit"
  "Select a wallet"
  "Please"
  "Deposit Wallet"
  "Interest Wallet"
  "Error"
  "Trx Type"
  "Approved"
  "Accept"
  "Enabled"
  "Disabled"
  "Succeed"
  "Pending"
  "Rejected"
  "Reject"
  "Completed"
  "Transaction Type"
  "Operation Type"
  "History From"
  "From Currency"
  "To Currency"
  "OTP"
  "Money Requests"
  "More Options"
  "Paid"
  "Unpaid"
  "Unpublished"
  "Please, fill up invoice to field"
  "Please, fill up email field"
  "Please, fill up address field"
  "Please, select your wallet"
  "Please, fill up item name field"
  "Please, fill up amount field"
  "Valid agent for money out"
  "Agent not found"
  "Valid merchant for make payment"
  "Merchant not found"
  "Valid agent for transaction"
  "User doesn't exists"
  "will be reduced from your"
  "Are you sure want to confirm?"
  "Image downloaded successfully"
  "( Last 7 days )"
  "Send Code"
  "You must agree with our privacy & policies"];

void main(){
  var  map = {};
 for(int i=0;i<list.length;i++){
   map["${list[i]}"]=list[i];
 }


 map.forEach((key, value) {
   print("------$key: v----$value ");
 });

}
